### ISSUE TITLE
DynMap does not load

### ISSUE THREAD

**Issue by satreix** [dockhippie/minecraft-forge#10]
When running the docker image, I get the following error:

"The modid Dynmap is not the same as it's lowercase version. Lowercasing is enforced in 1.11"

More context:

```[10:24:29] [Server thread/INFO] [FML]: MinecraftForge v13.20.0.2214 Initialized
[10:24:29] [Server thread/INFO] [FML]: Replaced 232 ore recipes
[10:24:29] [Server thread/INFO] [FML]: Found 1 mods from the command line. Injecting into mod discoverer
[10:24:29] [Server thread/INFO] [FML]: Searching /minecraft/mods for mods
[10:24:30] [Server thread/WARN] [FML]: ****************************************
[10:24:30] [Server thread/WARN] [FML]: * The modid Dynmap is not the same as it's lowercase version. Lowercasing is enforced in 1.11
[10:24:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:147)
[10:24:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:130)
[10:24:30] [Server thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:24:30] [Server thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:24:30] [Server thread/WARN] [FML]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:24:30] [Server thread/WARN] [FML]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)...
[10:24:30] [Server thread/WARN] [FML]: ****************************************
[10:24:30] [Server thread/ERROR] [FML]: Unable to construct net.minecraftforge.fml.common.Mod container
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:90) [ModContainerFactory.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:106) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:395) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:535) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [lh.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: The modid Dynmap is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
	at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:148) ~[FMLModContainer.class:?]
	at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:130) ~[FMLModContainer.class:?]
	... 16 more```

**Comment by satreix** [comment]
FYI I solved it quick and dirty by downloading DynMap again and updating the _optional_ script:

```bash
rm rootfs/minecraft/template/optional/Dynmap-2.4-forge-1.11.2.jar
wget https://addons-origin.cursecdn.com/files/2380/603/Dynmap-2.4-forge-1.11.2.jar -O rootfs/minecraft/template/optional/Dynmap-2.4-forge-1.11.2.jar
```

and:

```diff
diff --git a/rootfs/etc/s6/minecraft/optional b/rootfs/etc/s6/minecraft/optional
index 9bdf537..83d1f6f 100755
--- a/rootfs/etc/s6/minecraft/optional
+++ b/rootfs/etc/s6/minecraft/optional
@@ -2,7 +2,7 @@

 if [ -n "${SERVER_DYNMAP}" ] && [[ "${SERVER_DYNMAP}" == "true" || "${SERVER_DYNMAP}" == 1 ]]
 then
-  cp -f /minecraft/optional/DYNMAP.jar /minecraft/mods/DYNMAP.jar
+  cp -f /minecraft/optional/Dynmap-2.4-forge-1.11.2.jar /minecraft/mods/Dynmap-2.4-forge-1.11.2.jar
 else
-  rm -f /minecraft/mods/DYNMAP.jar
+  rm -f /minecraft/mods/Dynmap-2.4-forge-1.11.2.jar
 fi
```

**Comment by tboerger** [comment]
Thank you for the report, I will check the available versions and come back to this issue.

**Comment by tboerger** [comment]
This should be fixed with the latest builds.

**Comment by satreix** [comment]
Verified with webhippie/minecraft-forge:14.21.0. Thanks @tboerger
