### ISSUE TITLE
NoSuchMethodError in sun.security.util.ManifestEntryVerifier

### ISSUE THREAD

**Issue by mcbhenwood** [dockhippie/minecraft-forge#355]
Apologies if this is the wrong place to raise issues. Building against the `latest` version (or pulling it from Docker Hub) gives an error at startup. The same error is not found in the `latest` version of vanilla.
```
docker run --rm -it -p "25565:25565" webhippie/minecraft-forge:latest
...
Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:96)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:42)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:60)
```

**Comment by tboerger** [comment]
Sorry for the late response. Te latest tag haven't been a real latest tag, this will get updated with https://github.com/dockhippie/minecraft-forge/pull/356. The old latest tag contained v37.0.43, if you want to run a server with that version you coul launch `webhippie/minecraft-forge:37.0`. Beside that I have added various newer versions of forge.

**Comment by tboerger** [comment]
The mentioned PR will be merged directly after the builds are green.

**Comment by mcbhenwood** [comment]
Many thanks for taking the time to respond, and also thank you for the effort you are putting into making this containerisation so natural to adopt. It's very neat.
